apiVersion: v1
kind: Service
metadata:
  name: ngx-instance-0
  namespace: default
  labels:
    name: ngx-instance-0
  annotations:
    # NOTE: the following annotation is a beta feature and
    # only available in GCE/GKE and Azure as of now
    service.beta.kubernetes.io/external-traffic: OnlyLocal
spec:
  selector:
    app: ngx-instance-0-dep
  ports:
  - port: "<cluster-frontend-port from ConfigMap>"
    targetPort: "<cluster-frontend-port from ConfigMap>"
    name: public-cluster-port
    protocol: TCP
  - port: "<tm-pub-key-access from ConfigMap>"
    targetPort: "<tm-pub-key-access from ConfigMap>"
    name: tm-pub-key-access
    protocol: TCP
  - port: "<tm-p2p-port from ConfigMap>"
    targetPort: "<tm-p2p-port from ConfigMap>"
    protocol: TCP
    name: tm-p2p-port
  type: LoadBalancer
