###############################################################
# This config file runs bigchaindb:latest and connects to the #
# rethinkdb backend as a service                              #
###############################################################

apiVersion: v1
kind: Service
metadata:
  name: bdb-rdb-service
  namespace: default
  labels:
    name: bdb-rdb-service
spec:
  selector:
    app: bdb-rdb
  ports:
  - port: 9984
    targetPort: 9984
    name: bdb-rdb-api
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bdb-rdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bdb-rdb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: bdb-rdb
        image: bigchaindb/bigchaindb:latest
        args:
        - start
        env:
        - name: BIGCHAINDB_DATABASE_HOST
          value: rdb-service
        - name: BIGCHAINDB_DATABASE_PORT
          value: "28015"
        - name: BIGCHIANDB_DATABASE_BACKEND
          value: rethinkdb
        - name: BIGCHAINDB_DATABASE_NAME
          value: bigchain
        - name: BIGCHAINDB_SERVER_BIND
          value: 0.0.0.0:9984
        - name: BIGCHAINDB_KEYPAIR_PUBLIC
          value: EEWUAhsk94ZUHhVw7qx9oZiXYDAWc9cRz93eMrsTG4kZ
        - name: BIGCHAINDB_KEYPAIR_PRIVATE
          value: 3CjmRhu718gT1Wkba3LfdqX5pfYuBdaMPLd7ENUga5dm
        - name: BIGCHAINDB_BACKLOG_REASSIGN_DELAY
          value: "120"
        - name: BIGCHAINDB_KEYRING
          value: ""
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9984
          hostPort: 9984
          name: bdb-port
          protocol: TCP 
        volumeMounts:
        - name: bigchaindb-data
          mountPath: /data
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
        livenessProbe:
          httpGet:
            path: /
            port: 9984
          initialDelaySeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9984
          initialDelaySeconds: 15
          timeoutSeconds: 10
      restartPolicy: Always
      volumes:
      - name: bigchaindb-data
        hostPath:
          path: /disk/bigchaindb-data
