version: '3'

services:
  bdocs:
    build:
      context: .
      dockerfile: ./compose/bigchaindb-server/Dockerfile
      args:
        backend: localmongodb
    volumes:
      - .:/usr/src/app/
    command: make -C docs/server html
  vdocs:
    image: nginx
    ports:
      - '33333:80'
    volumes:
      - ./docs/server/build/html:/usr/share/nginx/html
