version: '2'

services:
  mdb:
    image: mongo:3.4.3
    volumes:
      - ./tests/backend/mongodb-ssl/certs/mongodb.pem:/etc/ssl/private/mongodb.pem
      - ./tests/backend/mongodb-ssl/certs/ca-chain.cert.pem:/etc/ssl/ca-chain.pem
      - ./tests/backend/mongodb-ssl/certs/crl.pem:/etc/ssl/crl.pem
    command: mongod --replSet=bigchain-rs --sslMode=requireSSL --sslCAFile=/etc/ssl/ca-chain.pem --sslCRLFile=/etc/ssl/crl.pem --sslPEMKeyFile=/etc/ssl/private/mongodb.pem

  bdb:
    environment:
      BIGCHAINDB_DATABASE_SSL: 1
      BIGCHAINDB_DATABASE_CA_CERT: /etc/ssl/ca-chain.pem
      BIGCHAINDB_DATABASE_CRLFILE: /etc/ssl/crl.pem
      BIGCHAINDB_DATABASE_CERTFILE: /etc/ssl/certs/bigchaindb.cert.pem
      BIGCHAINDB_DATABASE_KEYFILE: /etc/ssl/private/bigchaindb.key.pem
      BIGCHAINDB_MDB_PEM_KEY_TEST: /etc/ssl/private/
    volumes:
      - ./tests/backend/mongodb-ssl/ca:/root/ca
      - ./tests/backend/mongodb-ssl/certs/ca-chain.cert.pem:/etc/ssl/ca-chain.pem
      - ./tests/backend/mongodb-ssl/certs/bigchaindb.cert.pem:/etc/ssl/certs/bigchaindb.cert.pem
      - ./tests/backend/mongodb-ssl/certs/bigchaindb.key.pem:/etc/ssl/private/bigchaindb.key.pem
      - ./tests/backend/mongodb-ssl/certs/crl.pem:/etc/ssl/crl.pem
      - ./tests/backend/mongodb-ssl/certs/mongodb.pem:/etc/ssl/private/mongodb.pem
