#########################################################################
# This YAML file desribes a ConfigMap with a valid list of IP addresses #
# that can connect to the MongoDB instance.                             #
#########################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-whitelist
  namespace: default
data:
  # ':' separated list of allowed hosts
  allowed-hosts: 192.168.0.0/16:10.0.2.0/24
