---
# ansible/roles/db_storage/tasks/main.yml

#- name: Ensure the /data directory (for DB storage) exists
#  file: path=/data state=directory

- name: Format the block storage device at /dev/xvdp with an ext4 file system
  filesystem: fstype=ext4 dev=/dev/xvdp
  become: true

# Note that this also modifies /etc/fstab so the mount will persist through a crash
- name: Ensure /data dir exists and is mounted on /dev/xvdp + update /etc/fstab
  mount: name=/data src=/dev/xvdp fstype=ext4 state=mounted
  become: true

# After allowing the above to proceed,
# I did "cat /etc/fstab" and got:
# LABEL=cloudimg-rootfs	/	 ext4	defaults,discard	0 0
# /dev/xvdp /data ext4 defaults 0 0

# Let's change "defaults 0 0" to "defaults,nofail,nobootwait 0 2"

- name: Ensure any old edit_etc_fstab.py file is deleted
  file: name=/tmp/edit_etc_fstab.py state=absent

- name: Copy local Python script edit_etc_fstab.py to the remote host
  copy: src={{role_path}}/tasks/edit_etc_fstab.py dest=/tmp/edit_etc_fstab.py

- name: Run edit_etc_fstab.py using Python 3
  shell: /usr/bin/python3 /tmp/edit_etc_fstab.py
  become: true

- name: Ensure /tmp/edit_etc_fstab.py is deleted
  file: name=/tmp/edit_etc_fstab.py state=absent

# Modify the I/O scheduler? Is that even a good idea?
# Must do this in /sys/block/xvdp/queue/scheduler
# and also with grub (so the I/O scheduler stays changed on reboot)
# Example: https://gist.github.com/keithchambers/80b60559ad83cebf1672

