---
deploy_docker: false #[true, false]
docker_cluster_size: 1
upstart: "/bigchaindb/scripts/bootstrap.sh"
bdb_hosts:
  - name: "bdb-node-01"
    box:
      name: "ubuntu/xenial64"
    ram: "2048"
    vcpus: "1"
    network:
      ip: "10.20.30.20"
      type: "private_network"
  - name: "bdb-node-02"
    box:
      name: "centos/7"
    ram: "2048"
    vcpus: "1"
    network:
      ip: "10.20.30.30"
      type: "private_network"
  - name: "bdb-node-03"
    box:
      name: "bento/fedora-24"
    ram: "2048"
    vcpus: "1"
    network:
      ip: "10.20.30.40"
      type: "private_network"
