---
deploy_docker: false #[true, false]
docker_replset_size: 1
upstart: "/bigchaindb/scripts/bootstrap.sh"
bdb_hosts:
  - name: "config-node"
    box:
      name: "ubuntu/xenial64"
    ram: "2048"
    vcpus: "2"
    network:
      ip: "10.20.30.40"
      type: "private_network"