---
# ansible/roles/common/tasks/main.yml
# Note: "become: true" basically means "become root user for this task" i.e. sudo <cmd>
# See https://docs.ansible.com/ansible/become.html

- name: Do the equivalent of "sudo apt-get update"
  apt: update_cache=yes
  become: true

- name: Uninstall ntpdate (deprecated)
  apt: name=ntpdate state=absent
  become: true
  tags: ntp

- name: Update all installed packages to their latest versions
  apt: upgrade=dist
  become: true

- name: Install ntp
  apt: name=ntp state=latest update_cache=yes
  become: true
  tags: ntp

#- name: Configure ntp file
#  template: src=ntp.conf.j2 dest=/etc/ntp.conf
#  tags: ntp
  # "restart ntp" is the name of a handler (in common/handlers/main.yml)
#  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=yes
  become: true
  tags: ntp

#- name: test to see if selinux is running
#  command: getenforce
#  register: sestatus
#  changed_when: false
