apiVersion: v1
kind: Service
metadata:
  name: mdb-instance-0
  namespace: default
  labels:
    name: mdb-instance-0
spec:
  selector:
    app: mdb-instance-0-ss
  ports:
  - port: 27017
    targetPort: 27017
    name: mdb-port
  type: ClusterIP
  clusterIP: None
