###########################################################
# This section file desribes a k8s pvc for mongodb dbPath #
###########################################################
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-db-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: slow-db
spec:
  accessModes:
  - ReadWriteOnce
  # FIXME(Uncomment when ACS supports this!)
  # persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 20Gi
---
#############################################################
# This YAML section desribes a k8s pvc for mongodb configDB #
#############################################################
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-configdb-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: slow-configdb
spec:
  accessModes:
  - ReadWriteOnce
  # FIXME(Uncomment when ACS supports this!)
  # persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 1Gi
