########################################################
# This YAML file desribes a k8s pvc for mongodb dbPath #
########################################################

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-db-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: slow-db
spec:
  accessModes:
  - ReadWriteOnce
  # FIXME(Uncomment when ACS supports this!)
  # persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 20Gi
