apiVersion: v1
kind: Service
metadata:
  # Name of BigchainDB instance you are trying to connect to
  # name: "bdb-instance-0"
  name: "<remote-bdb-host>"
  namespace: default
spec:
  ports:
spec:
  ports:
  - port: 26656
    name: p2p
  - port: 26657
    name: pubkey
  - port: 9986
    name: nginx
  type: ExternalName
  # FQDN of remote cluster/NGINX instance
  #externalName: "nginx-instance-for-bdb-instance-0.westeurope.cloudapp.azure.com"
  externalName: "<dns-name-remote-nginx>"

