apiVersion: v1
kind: Service
metadata:
  name: bdb-instance-0
  namespace: default
  labels:
    name: bdb-instance-0
spec:
  selector:
    app: bdb-instance-0-dep
  ports:
  - port: 9984
    targetPort: 9984
    name: bdb-port
  - port: 9985
    targetPort: 9985
    name: bdb-ws-port
  type: ClusterIP
  clusterIP: None
