###############################################################
# This config file runs bigchaindb:master as a k8s Deployment #
# and it connects to the mongodb backend on a separate pod    #
###############################################################

apiVersion: v1
kind: Service
metadata:
  name: bdb
  namespace: default
  labels:
    name: bdb
spec:
  selector:
    app: bdb
  ports:
  - port: 9984
    targetPort: 9984
    name: bdb-port
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bdb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: bigchaindb
        image: bigchaindb/bigchaindb:master
        args:
        - start
        env:
        - name: BIGCHAINDB_DATABASE_HOST
          value: mdb
        - name: BIGCHAINDB_DATABASE_PORT
          # TODO(Krish): remove hardcoded port
          value: "27017"
        - name: BIGCHAINDB_DATABASE_REPLICASET
          value: bigchain-rs
        - name: BIGCHAINDB_DATABASE_BACKEND
          value: mongodb
        - name: BIGCHAINDB_DATABASE_NAME
          value: bigchain
        - name: BIGCHAINDB_SERVER_BIND
          value: 0.0.0.0:9984
        - name: BIGCHAINDB_KEYPAIR_PUBLIC
          value: EEWUAhsk94ZUHhVw7qx9oZiXYDAWc9cRz93eMrsTG4kZ
        - name: BIGCHAINDB_KEYPAIR_PRIVATE
          value: 3CjmRhu718gT1Wkba3LfdqX5pfYuBdaMPLd7ENUga5dm
        - name: BIGCHAINDB_BACKLOG_REASSIGN_DELAY
          value: "120"
        - name: BIGCHAINDB_KEYRING
          value: ""
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9984
          hostPort: 9984
          name: bdb-port
          protocol: TCP 
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
        livenessProbe:
          httpGet:
            path: /
            port: 9984
          initialDelaySeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 9984
          initialDelaySeconds: 15
          timeoutSeconds: 10
      restartPolicy: Always
