---
# ansible/roles/install_rethinkdb/tasks/main.yml

# Note: the .list extension will be added to the rethinkdb filename automatically
- name: >
    Ensure RethinkDB's APT repository for Ubuntu trusty is present
    in /etc/apt/sources.list.d/rethinkdb.list
  apt_repository:
    repo='deb http://download.rethinkdb.com/apt trusty main'
    filename=rethinkdb
    state=present
  become: true

- name: Ensure RethinkDB's public GPG key is in the set of APT keys
  apt_key: url=http://download.rethinkdb.com/apt/pubkey.gpg state=present
  become: true

- name: Ensure the latest rethinkdb Ubuntu package is installed
  apt: name=rethinkdb state=latest update_cache=yes
  become: true

- name: Ensure the /data directory's owner and group are both 'rethinkdb'
  file: path=/data state=directory owner=rethinkdb group=rethinkdb
  become: true
