# Certificate data should be base64 encoded before embedding them here by using
# `cat cert.pem | base64 -w 0 > cert.pem.b64` and then copy the resulting
# value here. Same goes for cert.key.
# Ref: https://kubernetes.io/docs/concepts/configuration/secret/

apiVersion: v1
kind: Secret
metadata:
  name: certs
type: Opaque
data:
  cert.pem: <certificate data here>
  cert.key: <key data here>
