## vars is common environment variables for this BigchaindB node
apiVersion: v1
kind: ConfigMap
metadata:
  name: vars
  namespace: default
data:
  # MongoDB
  mdb-instance-name: "<name of the mdb instance>"
  # BigchainDB
  bdb-instance-name: "<name of the bdb instance>"
  # NGINX
  ngx-instance-name: "<name of the ngx instance>"
  # MongoDB Monitoring Agent
  mdb-mon-instance-name: "<name of the mdb monitoring agent instance>"
  # MongoDB Backup Agent
  mdb-bak-instance-name: "<name of the mdb backup agent instance>"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-whitelist
  namespace: default
data:
  # We only support "all"" currently
  allowed-hosts: "all"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bdb-keyring
  namespace: default
data:
  # Colon-separated list of all *other* nodes' BigchainDB public keys
  # with no base64 encoding anywhere
  bdb-keyring: "<':' separated list of public keys>"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bdb-public-key
  namespace: default
data:
  # BigchainDB public key of *this* node, not base64-encoded.
  # Example: "EPQk5i5yYpoUwGVM8VKZRjM8CYxB6j8Lu8i8SG7kGGce"
  bdb-public-key: "<public key>"
