#######################################################
# This YAML file desribes a ConfigMap for the cluster #
#######################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: mdb-mon
  namespace: default
data:
  api-key: "<api key here>"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mdb-backup
  namespace: default
data:
  api-key: "<api key here>"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mdb-fqdn
  namespace: default
data:
  fqdn: mdb-instance-0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-whitelist
  namespace: default
data:
  allowed-hosts: "all"

