---
- name: "bdb-node-01" # Instance name
  box:
    name: "ubuntu/xenial64" # Box name
  ram: "2048"
  vcpus: "2"
  setup_type: "quickstart" # Currently, only quickstart is supported.
  deploy_docker: true # [true, false]
  network:
    ip: "10.20.30.50"
    type: "private_network" # Currently, only private network is supported.
  upstart: "/bigchaindb/scripts/bootstrap.sh" # Path to upstart script
