---
- name: Removing apt cache lists
  file:
    path: /var/lib/apt/lists/*
    state: absent
    force: yes
  tags: [mongodb]

- name: Update Cache
  apt: update_cache=yes
  tags: [mongodb]

- name: Add APT Key | apt
  apt_key:
    keyserver: "{{ apt_keyserver }}"
    id: "{{ apt_key_fingerprint }}"
    state: present
  tags: [mongodb]

- name: Add MongoDB repo and update cache | apt
  apt_repository:
    repo: "{{ mongodb_apt_repo }}"
    state: present
    update_cache: no
  tags: [mongodb]

- name: Install MongoDB | apt
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ mongodb_package }}"
  tags: [mongodb]