---
- name: Check Docker Service
  systemd:
    name: docker
    enabled: yes
    state: started
  tags: [mongodb]

- name: Creating BDB Docker network
  docker_network:
    name: "{{ bdb_docker_net_name }}"
    ipam_options:
      subnet: "{{ bdb_docker_default_subnet }}"
    driver_options:
      com.docker.network.bridge.enable_icc": "true"
      com.docker.network.bridge.enable_ip_masquerade": "true"
      com.docker.network.bridge.host_binding_ipv4": "0.0.0.0"
      com.docker.network.driver.mtu: "1500"
    state: present
  tags: [mongodb]

- name: Running MongoDB Docker
  docker_container:
    name: "{{ mongodb_docker_name }}{{ item }}"
    hostname: "{{ mongodb_docker_name }}{{ item }}"
    image: "{{ mongodb_docker_image }}"
    detach: true
    published_ports:
      - "{{ bdb_docker_default_gw }}:{{ (mongodb_port|int + item|int)|string }}:{{ mongodb_port }}"
    restart_policy: always
    volumes:
      - "{{ mongodb_host_mount_dir }}{{ item|string }}/db:{{ mongodb_storage_path }}"
      - "{{ mongodb_host_mount_dir }}{{ item|string }}/configdb:{{ mongodb_config_path }}"
      - "{{ mongodb_host_config }}:/bdb_config"
    state: started
    keep_volumes: true
    entrypoint: /entrypoint.sh --replSet=bigchain-rs
    networks:
      - name: "{{ bdb_docker_net_name }}"
  register: mongo_container_info
  with_sequence: start=0 end="{{ docker_cluster_size|int - 1 }}" stride=1
  tags: [mongodb]

- name: Set facts for MongoDB containers
  set_fact:
    mongodb{{ item }}={{ mongo_container_info.results[item|int].ansible_facts.docker_container.NetworkSettings.IPAddress }}
  with_sequence: start=0 end="{{ docker_cluster_size|int - 1 }}" stride=1
  tags: [mongodb]