---

- include: debian.yml
  when: distribution_name == "debian" or distribution_name == "ubuntu"

- include: centos.yml
  when: distribution_name == "centos" or distribution_name == "red hat enterprise linux"

- include: fedora.yml
  when: distribution_name == "fedora"

- include: common.yml