apiVersion: v1
kind: Service
metadata:
  name: tm-instance-1
  namespace: default
  labels:
    name: tm-instance-1
spec:
  selector:
    app: tm-instance-1-ss
  ports:
    - port: "<tm-p2p-port from ConfigMap>"
      targetPort: "<tm-p2p-port from ConfigMap>"
      name: p2p
      protocol: TCP
    - port: "<tm-rpc-port from ConfigMap>"
      targetPort: "<tm-rpc-port from ConfigMap>"
      name: rpc
      protocol: TCP
    - port: "<tm-pub-key-access from ConfigMap>"
      targetPort: "<tm-pub-key-access from ConfigMap>"
      name: pub-key-access
      protocol: TCP
  clusterIP: None
