---
- name: Upgrade pip
  shell: "pip3 install --upgrade pip"
  when: python_pip_upgrade
  tags: [bigchaindb]

- name: Upgade setuptools
  shell: "pip3 install --upgrade setuptools"
  when: python_setuptools_upgrade
  tags: [bigchaindb]

- name: Install BigchainDB
  shell: "pip3 install bigchaindb"
  tags: [bigchaindb]

- name: Configure BigchainDB
  shell: "bigchaindb -y configure {{ backend_db }}"
  environment:
    BIGCHAINDB_SERVER_BIND:  "{{ bigchaindb_server_bind }}"
  tags: [bigchaindb]

- name: MongoDB Process Check
  shell: pgrep mongod | wc -l
  register: mdb_pchk
  tags: [bigchaindb]

- name: BigchainDB Process Check
  shell: pgrep bigchaindb | wc -l
  register: bdb_pchk
  tags: [bigchaindb]

- name: Start BigchainDB
  become: yes
  shell: "bigchaindb start > {{ bigchaindb_log_file }} 2>&1 &"
  when: mdb_pchk.stdout| int >= 1 and bdb_pchk.stdout| int == 0
  tags: [bigchaindb]